language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci -package ./dtls