language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint
script:
  - go test -v -race -covermode=atomic -coverprofile=stun.coverprofile ./stun
  - 'echo "mode: atomic" > .coverage && grep -h -v "mode: atomic" *.coverprofile >> .coverage'
  - $HOME/gopath/bin/goveralls -coverprofile=.coverage -service=travis-ci
